version: '3'

services:
  react:
    build: front-end/
    depends_on:
      - 'database'
    ports: 
      - '3000:3000'

  server:
    build: server/
    depends_on:
      - 'database'
    ports:
      - '8080:8080'
    command: sh -c "npx knex migrate:latest && npx knex seed:run && npm start"

  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - '5432:5432'